[package]
authors = ["Alexander Thaller <alexander.thaller@trivago.com>"]
name = "lablog"
version = "0.1.0"

[dependencies]
error-chain = "0.11"
log = "0.3"
loggerv = "0.4"
regex = "0.2"
tempdir = "0.3"
xdg = "2.1"

[dependencies.clap]
features = ["yaml"]
version = "2.27"

[dependencies.lablog_store]
path = "../../lib/store"

[dependencies.lablog_store_csv]
path = "../../lib/store_csv"

[dev-dependencies]
chrono = "0.4"
pretty_assertions = "0.4"
