[package]
authors = ["Alexander Thaller <alexander.thaller@trivago.com>"]
name = "lablog"
version = "0.1.0"

[dependencies]
log = "0.3.8"
loggerv = "0.4.0"
xdg = "2.1.0"

[dependencies.clap]
features = ["yaml"]
version = "2.27.1"

[dependencies.lablog_store]
path = "../../lib/store"

[dependencies.lablog_store_csv]
path = "../../lib/store_csv"
