[package]
authors = ["Alexander Thaller <alexander.thaller@trivago.com>"]
name = "converter"
version = "0.1.0"

[dependencies]
error-chain = "0.11.0"
log = "0.3.8"
loggerv = "0.4.0"

[dependencies.clap]
features = ["yaml"]
version = "2.27.1"
